server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://106.15.3.13:8085/eureka/
#    register-with-eureka: false
#    fetch-registry: false


spring:
  datasource:
    url: jdbc:mysql://47.103.9.250:3306/soa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: userservice
  redis:
    host: 47.103.9.250
    port: 6379
    jedis:
      pool:
        max-active: 8
  rabbitmq:
    host: 47.102.204.30
    port: 5672
    username: itcast
    password: 123321
    virtualHost: /

