server:
  port: 8090 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
  instance:
    hostname: localhost

#当前服务名称
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: Mysql123456+
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: distribution-service