server:
  port: 8084

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #当前zuul网关想要注册到哪个注册中心这里注册到之前搭的9000上。

#路由规则定义。这里定义两种路由规则route1和route2
#，代表访问网关/test01/**或/test02/**时。
#路由到服务名为 eurekaservice1或 eureka
#service2中的服务集群去。

zuul:
  routes:
    route1:
      path: /user-service/**
      serviceId: userservice
      url: http://47.103.9.250:9000
    route2:
      taxi-service:
        path: /taxi-service/**
        serviceId: taxiservice
        #url: http://106.15.3.13:9001
    route3:
      path: /distribution-service/**
      serviceId: distribution-service
      url: http://106.15.3.13:9002
    route4:
      path: /order-service/**
      serviceId: orderservice
      url: http://106.15.3.13:9003
    route5:
      path: /position-service/**
      serviceId: position-service
      url: http://139.224.251.185:9004
    route6:
      path: /map-service/**
      serviceId: map
      url: http://47.102.204.30:9005
    route8:
      path: /ordertaking-service/**
      serviceId: ordertakingservice
      url: http://106.15.3.13:9007
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  max:
    host:
      connections: 5000 #最大请求时间
  host:  #等待
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  eureka:
    enabled: false

taxi-service:
  ribbon:
    listOfServers: http://106.15.3.13:9001,http://101.132.32.186:9001

#  sensitive-headers: Access-Control-Allow-Origin
#  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options,token
