server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://139.224.251.185:8761/eureka/

spring:
  application:
    name: Orderservice
  datasource:
    url: jdbc:mysql://116.62.208.68:3306/didi?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: 47.102.204.30
    port: 5672
    username: itcast
    password: 123321
    virtualHost: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true