server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://139.224.251.185:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false


spring:
  datasource:
    url: jdbc:mysql://47.103.9.250:3306/soa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: userservicechao
  redis:
    host: 47.103.9.250
    port: 6379
    jedis:
      pool:
        max-active: 8


