server:
  port: 9004 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

#  instance:
#    hostname: 127.0.0.1

#当前服务名称
spring:
  application:
    name: position-service