server:
  port: 9004

#spring:
#  datasource:
#    tdengine-server:
#      jdbc-url: jdbc:TAOS://139.224.251.185:6030/taxi?user=root&password=taosdata
#      username: root
#      password: taosdata
#      type: com.zaxxer.hikari.HikariDataSource      # Hikari连接池的设置
#      minimum-idle: 5                 #最小连接
#      maximum-pool-size: 15        #最大连接
#      auto-commit: true        #自动提交
#      idle-timeout: 30000        #最大空闲时常
#      pool-name: TDengineDruidCP        #连接池名
#      max-lifetime: 1800000        #最大生命周期
#      connection-timeout: 30000        #连接超时时间
#      connection-test-query: show tables
#
#    mysql-server:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      #    url: jdbc:mysql://192.168.100.9:3688/hailitong?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowMultiQueries=true
#      jdbc-url: jdbc:mysql://192.168.100.9:3688/hailitong?useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowMultiQueries=true
#      username: root
#      password: xiaoodu888keji
#      type: com.zaxxer.hikari.HikariDataSource
#      minimum-idle: 5                 #最小连接
#      maximum-pool-size: 15        #最大连接
#      auto-commit: true        #自动提交
#      idle-timeout: 30000        #最大空闲时常
#      pool-name: MysqlDruidCP        #连接池名
#      max-lifetime: 1800000        #最大生命周期
#      connection-timeout: 30000        #连接超时时间

#mybatis
mybatis:
  type-aliases-package: com.entity
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql
    call-setters-on-nulls: true  #设置查询字段为空时，也返回该字段
    map-underscore-to-camel-case: true

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


pattern:
  dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 47.102.204.30 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1
  application:
    name: position-service

